#!/bin/bash
if [ ${EUID} -ne 0 ]; then
    echo "Run as root"
    exit 1
fi
case $1 in
	on)
		echo 0 > /sys/class/net/wlp0s20f3/phy80211/rfkill1/state
	;;
	off)
		echo 1 > /sys/class/net/wlp0s20f3/phy80211/rfkill1/state
	;;
esac
