#!/bin/bash

alias vim='nvim'
alias vi='nvim'
alias e='nvim'

alias k='zk'
alias kj='nvim +"ZkIndex"'
alias kn='nvim +"ZkIndex"'

alias ve='source .env/bin/activate'

alias al='ssh-add -L'
alias aa='ssh-add'

if [ -f /etc/os-release ]; then
    source /etc/os-release
fi

if [ "$ID" == "fedora" ]; then
    alias aac='ssh-add -s /usr/lib64/pkcs11/opensc-pkcs11.so'
else
    alias aac='ssh-add -s /usr/lib64/x86_64-linux-gnu/opensc-pkcs11.so'
fi

alias ar='vanilla::reset_agent'
alias arou='vanilla::agent_roulette'

alias ls='ls --color=auto'
if [ -x bat ]; then
    alias cat='bat'
    alias c='bat'
    alias b='bat'
else
    alias c='cat'
    alias b='cat'
fi

if [ -x rg ]; then
    alias grep='rg'
else
    alias grep='grep --color=auto'
fi

if [ -x doas ]; then
    alias sudo='doas'
fi

# why lead with l?
alias s='ls -CF'
alias a='ls -lA'
alias sa='ls -la'

alias f='fg'
# alias fd='vanilla::find -d'
# alias fdi='vanilla::find -d -i'
# alias ff='vanilla::find'
# alias ffi='vanilla::find -i'

alias g='git'
alias gc='git -C'

alias h='man'
alias i='invoke'

# our functions
alias np="vanilla::new_project"

alias m='make'
alias md='mkdir'

alias p='python3'

alias so='vanilla::source'

if [ -x zstd ]; then
    alias rsync='rsync --zc=zstd'
fi

if [ -x tree ]; then
    # Get the major version number
    if [ $(tree --version | grep -Po 'v\K\d') -lt 2 ]; then
        alias t='tree'
    else
        alias t='tree --gitignore'
    fi
else
    alias t='vanilla::tree'
fi

alias show='swayimg'
alias today='date +%F'

alias r='rm'
alias rf='rm -rf'
alias rd='rmdir'

alias pce='podman exec -it'
alias pck='podman stop -t0'
alias pcs='podman start'
alias pcr='podman remove'
alias pci='vanilla::podman_shell'
alias psall='podman ps -qa|xargs podman start'

alias nwl='networkctl list'
alias nws='networkctl status'
alias nwr='sudo networkctl reload'
alias nwrc='sudo networkctl reconfigure'
alias nwd='sudo networkctl down'
alias nwu='sudo networkctl up'
alias nwrs='sudo systemctl restart systemd-networkd'

