#!/bin/bash

alias vim='nvim'
alias vi='nvim'
alias e='nvim'

alias ve='source .env/bin/activate'

alias ls='ls --color=auto'
if [ $(which rg) ]; then
    alias grep='rg'
else
    alias grep='grep --color=auto'
fi

# why lead with l?
alias s='ls -CF'
alias a='ls -lA'
alias sa='ls -la'

alias f='fg'
# alias fd='vanilla::find -d'
# alias fdi='vanilla::find -d -i'
# alias ff='vanilla::find'
# alias ffi='vanilla::find -i'

alias g='git'
alias gc='git -C'

alias h='man'
alias i='invoke'

# our functions
alias np="vanilla::new_project"

alias m='make'
alias md='mkdir'

alias p='python3'

alias so='vanilla::source'

if [ $(which tree) ]; then
    # Get the major version number
    VERSION=$(tree --version | grep -Po '[0-9](?=(\.[0-9]){2})')
    if [ ${VERSION} -lt 2  ]; then
        alias t='tree'
    else
        alias t='tree --gitignore'
    fi
else
    alias t='vanilla::tree'
fi

alias r='rm'
alias rf='rm -rf'
alias rd='rmdir'
