#!/bin/bash

alias vi='nvim'
alias vim='nvim'
alias e='nvim'

alias venv='source .env/bin/activate'

alias ls='ls --color=auto'
if [ $(which rg) ]; then
    alias grep='rg'
else
    alias grep='grep --color=auto'
fi

alias l='ls -CF'
alias la='ls -lA'
alias ll='ls -l'

alias f='fg'

alias g='git'
alias gc='git -C'

alias h='man'
alias i='invoke'

# our functions
alias np="srak::new_project"

alias m='make'

alias p='python3'

alias so='srak::source'

alias t='tree'
