#!/bin/bash

alias vi='nvim'
alias vim='nvim'
alias venv='source .env/bin/activate'
alias ls='ls --color=auto'
alias grep='grep --color=auto'

alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'


# our functions
alias np="srak::new_project"
