#!/bin/bash

function srak::argparse() {
    return 0

}

function srak::ipify() {
    curl -sL https://api.ipify.org
}

function srak::newproj() {
    declare -i PIP
    if [ "$1" == "--nopip" ]; then
        PIP=0
        shift
    fi
    if [ ! -d $1 ]; then
        mkdir $1
    fi
    cd $1
    git init
    if [ $PIP -eq 1 ]; then
        python3 -m venv --prompt $1 .env
    fi
}

function srak::setup_agent() {
    if [ -S /run/user/${UID}/keyring/ssh ]; then
        # ubuntu
        export SSH_AUTH_SOCK=/run/user/${UID}/keyring/ssh
    fi
    if [ -S /run/user/${UID}/openssh_agent ]; then
        # debian
        export SSH_AUTH_SOCK=/run/user/${UID}/openssh_agent
    fi
}
