#!/bin/bash

function vanilla::argparse() {
    return 0
}

function vanilla::jsonify() {
    local STR="{"
    local K=${1%=*}
    local V=${1#*=}
    STR="$STR\"$K\": \"$V\""
    shift
    while [ $# -gt 0 ]; do
        K=${1%=*}
        V=${1#*=}
        STR="$STR, \"$K\": \"$V\""
        shift
    done
    STR="$STR}"
    echo $STR
}

function vanilla::ipify() {
    curl -sL https://api.ipify.org
}

function vanilla::newproj() {
    declare -i PIP
    if [ "$1" == "--nopip" ]; then
        PIP=0
        shift
    fi
    if [ ! -d $1 ]; then
        mkdir $1
    fi
    cd $1
    git init
    if [ $PIP -eq 1 ]; then
        python3 -m venv --prompt $1 .env
    fi
}

function vanilla::setup_agent() {
    if [ -S /run/user/${UID}/keyring/ssh ]; then
        # ubuntu
        export SSH_AUTH_SOCK=/run/user/${UID}/keyring/ssh
    fi
    if [ -S /run/user/${UID}/openssh_agent ]; then
        # debian
        export SSH_AUTH_SOCK=/run/user/${UID}/openssh_agent
    fi
}

function vanilla::source() {
    source ${HOME}/.bashrc
}

function vanilla::find() {
    declare TYPE=""
    declare I=""
    if [ "$1" == "-d" ]; then
        TYPE="d"
        shift
    else
        TYPE="f"
    fi
    if [ "$1" == "-i" ]; then
        declare I="i"
        shift
    fi
    find . -${I}name \*$1\* -type ${TYPE}
}
