#!/bin/bash

if [ -f "/etc/profile" ]; then
    source "/etc/profile"
fi

if [ -n "${BASH_VERSION}" ]; then
    # include .bashrc if it exists
    if [ -z "${_VANILLA_SOURCED:-}" ]; then
        if [ -f "${HOME}/.bashrc" ]; then
            source "${HOME}/.bashrc"
        fi
    fi
fi
