#!/bin/bash

if [ -n "${BASH_VERSION}" ]; then
    # include .bashrc if it exists
    if [ -f "${HOME}/.bashrc" ]; then
	. "${HOME}/.bashrc"
    fi
fi

if [ -f /etc/profile ]; then
    source /etc/profile
fi

if [ -z ${_VANILLA_SOURCED:-} ]; then
    if [ -f ${HOME}/.bashrc ]; then
        source ${HOME}/.bashrc
    fi
fi

if [ -d "${HOME}/.cargo/env" ]; then
    source "${HOME}/.cargo/env"
fi
