#!/bin/bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

export HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
export HISTSIZE=1000
export HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '


export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    source /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    source /etc/bash_completion
  fi
fi

# TODO do setup logic for this agent?
# if we can tell we SSHd to the machine we shouldn't start an agent
# export SSH_AUTH_SOCK=/run/user/${UID}/openssh_agent
# if [ ! -S ${SSH_AUTH_SOCK} ]; then
#   eval `ssh-agent -D -a ${SSH_AUTH_SOCK}`
# fi

# env setup

export HISTCONTROL=ignoreboth
#export HISTIGNORE='fg:cd*:ls*:tomb*'
export PATH="${HOME}/.local/bin:${PATH}"

export EDITOR=nvim
export MANPAGER='nvim +Man!'

if [ -f "${HOME}/.bash_functions" ]; then
    source "${HOME}/.bash_functions"
fi
if [ -f "${HOME}/.bash_alias" ]; then
    source "${HOME}/.bash_alias"
fi

# post source

declare _VANILLA_SOURCED=true

# some things don't like TERM=foot
export TERM=xterm

if [ -z "${SSH_AUTH_SOCK:-}" ]; then
    if [ -z "${SSH_CONNECTION:-}" ]; then
        vanilla::setup_agent
    fi
fi

if [ -f "${HOME}/.cargo/env" ]; then
    source "${HOME}/.cargo/env"
fi
